### ISSUE TITLE
Setup instructions are wrong

### ISSUE THREAD

**Issue by punkpeye** [andybrandt/mcp-simple-openai-assistant#1]
```
python -m mcp-simple-openai-assistant
```

is saying:

```
/usr/local/bin/python: No module named mcp-simple-openai-assistant
```

```
python -m mcp_simple_openai_assistant
```

works though. so I think just an error in the instructions?

**Comment by punkpeye** [comment]
I also tried just `mcp-simple-openai-assistant`, but that gives

```
<coroutine object main at 0xffff95912890>
sys:1: RuntimeWarning: coroutine 'main' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by andyvntsys** [comment]
and this instruction did not work for me: ```
mcpServers": {
  "openai-assistant": {
    "command": "C:\\Users\\YOUR_USERNAME\\AppData\\Local\\Programs\\Python\\Python311\\python.exe",
      "args": ["-m", "mcp-simple-openai-assistant"],
      "env": {
        "OPENAI_API_KEY": "your-api-key-here"
  }
}
```

**Comment by andybrandt** [comment]
You are right, in the configuration files the module to run should always be referred to with underscores, not dashes. This is mistake in the README.md - just fixed it. Thanks for pointing it out.
